# Generated by Django 3.1.5 on 2022-05-16 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ssa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=50)),
                ('circle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.circle')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=13)),
                ('account_no', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('upc_date', models.DateField(blank=True, null=True)),
                ('upc_expiry_date', models.DateField(blank=True, null=True)),
                ('connection_type', models.CharField(blank=True, max_length=15, null=True)),
                ('avg_revenue', models.CharField(blank=True, max_length=100, null=True)),
                ('portout_apply_date', models.DateField(blank=True, null=True)),
                ('portout_date', models.DateField(blank=True, null=True)),
                ('port_status', models.CharField(blank=True, max_length=50, null=True)),
                ('called_counter', models.IntegerField(default=0)),
                ('reason_for_PO', models.CharField(choices=[('poor_network_coverage', 'Poor network coverage'), ('low_data_speed', 'Low data speed'), ('absence_of_4g', 'Absence of 4G'), ('poor_customer_care', 'Poor customer care'), ('recharge_issues', 'Recharge issues'), ('billing_issues', 'Billing issues'), ('high_tariff', 'High Tariff'), ('vas', 'Value Added Services'), ('others', 'Others'), ('not_answered', 'Not Answered'), ('select', 'Select reason')], default='select', help_text='Reason for opting PO', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('feedback_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.circle')),
                ('ssa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.ssa')),
            ],
            options={
                'ordering': ['-avg_revenue', 'circle', 'ssa', 'upc_date', 'msisdn'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('circle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.circle')),
                ('ssa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbacks.ssa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
